/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    mail: Mail;
    posts: Post;
    categories: Category;
    tags: Tag;
    comments: Comment;
    media: Media;
    tours: Tour;
    'tour-comments': TourComment;
    feedback: Feedback;
    reviews: Review;
    guides: Guide;
    languages: Language;
    nationalities: Nationality;
    provinces: Province;
    'tour-types': TourType;
    stories: Story;
    destinations: Destination;
    faqs: Faq;
    translations: Translation;
    slides: Slide;
    'navigation-menus': NavigationMenu;
    'site-settings': SiteSetting;
    'theme-settings': ThemeSetting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    mail: MailSelect<false> | MailSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    'tour-comments': TourCommentsSelect<false> | TourCommentsSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
    nationalities: NationalitiesSelect<false> | NationalitiesSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    'tour-types': TourTypesSelect<false> | TourTypesSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
    slides: SlidesSelect<false> | SlidesSelect<true>;
    'navigation-menus': NavigationMenusSelect<false> | NavigationMenusSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('en' | 'es' | 'it' | 'vi') | ('en' | 'es' | 'it' | 'vi')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es' | 'it' | 'vi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName: string;
  role: 'admin' | 'editor' | 'author' | 'contributor' | 'subscriber';
  status?: ('active' | 'inactive' | 'banned') | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  website?: string | null;
  socialLinks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  permissions?:
    | {
        permission?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  title?: string | null;
  altText?: string | null;
  caption?: string | null;
  description?: string | null;
  mediaType?: ('image' | 'video' | 'audio' | 'document' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail".
 */
export interface Mail {
  id: number;
  to: string;
  subject?: string | null;
  html?: string | null;
  text?: string | null;
  status?: ('pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  type: 'post' | 'page';
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  status?: ('draft' | 'published' | 'scheduled' | 'private' | 'trash') | null;
  author?: (number | null) | User;
  featuredImage?: (number | null) | Media;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  scheduledFor?: string | null;
  publishedAt?: string | null;
  viewCount?: number | null;
  commentCount?: number | null;
  allowComments?: boolean | null;
  seo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  relatedPosts?: (number | Post)[] | null;
  relatedStories?: (number | Story)[] | null;
  relatedGuides?: (number | Guide)[] | null;
  relatedTourTypes?: (number | TourType)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  order?: number | null;
  count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  publishedAt?: string | null;
  readTimeMinutes?: number | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  category?: string | null;
  relatedGuides?: (number | Guide)[] | null;
  relatedTourTypes?: (number | TourType)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  name: string;
  photo?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  cardNumber?: string | null;
  cardType?: ('international' | 'domestic') | null;
  cardIssuePlace?: string | null;
  cardIssueDate?: string | null;
  cardExpiryDate?: string | null;
  experienceYears?: number | null;
  bio?: string | null;
  slogan?: string | null;
  guideFeeUsd?: number | null;
  showOnFrontend?: boolean | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
    whatsapp?: string | null;
    zalo?: string | null;
    viber?: string | null;
    linkedin?: string | null;
  };
  spokenLanguages?:
    | {
        language: number | Language;
        level?: ('basic' | 'intermediate' | 'fluent' | 'native') | null;
        certificate?: string | null;
        id?: string | null;
      }[]
    | null;
  provinces?: (number | Province)[] | null;
  nationalities?: (number | Nationality)[] | null;
  tourTypes?: (number | TourType)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: number;
  name: string;
  code?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: number;
  name: string;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nationalities".
 */
export interface Nationality {
  id: number;
  name: string;
  code?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-types".
 */
export interface TourType {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  icon?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  post: number | Post;
  authorName: string;
  authorEmail: string;
  authorUrl?: string | null;
  content: string;
  status?: ('pending' | 'approved' | 'spam' | 'trash') | null;
  parent?: (number | null) | Comment;
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  code?: string | null;
  company?: string | null;
  name: string;
  summary?: string | null;
  itinerary?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  clientCount?: number | null;
  clientCountry?: string | null;
  clientCity?: string | null;
  guides?: (number | Guide)[] | null;
  status?: ('finished' | 'for_sale') | null;
  showFeedbackForm?: boolean | null;
  photos?:
    | {
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  provinces?: (number | Province)[] | null;
  tourTypes?: (number | TourType)[] | null;
  clientNationalities?: (number | Nationality)[] | null;
  guideLanguages?: (number | Language)[] | null;
  relatedPosts?: (number | Post)[] | null;
  relatedStories?: (number | Story)[] | null;
  price?: number | null;
  currency?: ('VND' | 'USD') | null;
  priceUnit?: ('per_person' | 'per_group') | null;
  durationDays?: number | null;
  groupSizeMin?: number | null;
  groupSizeMax?: number | null;
  departureSchedule?: string | null;
  highlights?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  excluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-comments".
 */
export interface TourComment {
  id: number;
  tour: number | Tour;
  authorName?: string | null;
  rating?: number | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  name?: string | null;
  country?: string | null;
  language?: string | null;
  rating?: number | null;
  message?: string | null;
  tour?: (number | null) | Tour;
  photo?: (number | null) | Media;
  status?: ('pending' | 'approved' | 'rejected') | null;
  source?: string | null;
  externalUrl?: string | null;
  reviewTitle?: string | null;
  visible?: boolean | null;
  featured?: boolean | null;
  feedbackSummary?: string | null;
  guide?: (number | null) | Guide;
  tourRef?: (number | null) | Tour;
  approvedAt?: string | null;
  review?: (number | null) | Review;
  rejectedAt?: string | null;
  rejectedBy?: string | null;
  rejectionReason?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  authorDisplay?: string | null;
  country?: string | null;
  language?: string | null;
  rating?: number | null;
  message?: string | null;
  tour?: (number | null) | Tour;
  tourName?: string | null;
  photoUrls?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  summary?: string | null;
  reviewType?: string | null;
  approvedAt?: string | null;
  feedback?: (number | null) | Feedback;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  slug: string;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  province?: (number | null) | Province;
  order?: number | null;
  status?: ('draft' | 'published') | null;
  tours?: (number | Tour)[] | null;
  tourTypes?: (number | TourType)[] | null;
  guides?: (number | Guide)[] | null;
  posts?: (number | Post)[] | null;
  stories?: (number | Story)[] | null;
  mustSee?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  mustDo?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  mustEat?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  seo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedTo?:
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'tour-types';
        value: number | TourType;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null);
  category?: string | null;
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  key: string;
  group?: string | null;
  value: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides".
 */
export interface Slide {
  id: number;
  title: string;
  subtitle?: string | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  active?: boolean | null;
  status?: ('draft' | 'published') | null;
  overlayOpacity?: number | null;
  alt?: string | null;
  startAt?: string | null;
  endAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus".
 */
export interface NavigationMenu {
  id: number;
  key: 'header' | 'footer';
  title?: string | null;
  published?: boolean | null;
  items?:
    | {
        label: string;
        href?: string | null;
        type?: ('internal' | 'external' | 'hash') | null;
        order?: number | null;
        parentId?: string | null;
        /**
         * Lucide icon name (e.g. Home, MapPin, Facebook) — required for all nav items.
         */
        icon: string;
        target?: ('_self' | '_blank') | null;
        visibleFor?:
          | {
              audience?: ('guest' | 'user' | 'admin') | null;
              id?: string | null;
            }[]
          | null;
        badge?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        area?: ('links' | 'legal' | 'social' | 'contact' | 'cta') | null;
        group?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  logoLight?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroCtaLabel?: string | null;
  heroMedia?: (number | null) | Media;
  aboutTitle?: string | null;
  aboutDescription?: string | null;
  aboutImage?: (number | null) | Media;
  missionStatement?: string | null;
  values?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  contact?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  social?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  copyright?: string | null;
  primaryColor?: string | null;
  accentColor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  primaryFont?: string | null;
  secondaryFont?: string | null;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  accentColor?: string | null;
  backgroundColor?: string | null;
  textColor?: string | null;
  linkColor?: string | null;
  headerStyle?: ('minimal' | 'classic' | 'modern') | null;
  footerStyle?: ('simple' | 'detailed') | null;
  customCSS?: string | null;
  customJS?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'mail';
        value: number | Mail;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'tour-comments';
        value: number | TourComment;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'languages';
        value: number | Language;
      } | null)
    | ({
        relationTo: 'nationalities';
        value: number | Nationality;
      } | null)
    | ({
        relationTo: 'provinces';
        value: number | Province;
      } | null)
    | ({
        relationTo: 'tour-types';
        value: number | TourType;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'translations';
        value: number | Translation;
      } | null)
    | ({
        relationTo: 'slides';
        value: number | Slide;
      } | null)
    | ({
        relationTo: 'navigation-menus';
        value: number | NavigationMenu;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'theme-settings';
        value: number | ThemeSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  status?: T;
  avatar?: T;
  bio?: T;
  website?: T;
  socialLinks?: T;
  permissions?:
    | T
    | {
        permission?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail_select".
 */
export interface MailSelect<T extends boolean = true> {
  to?: T;
  subject?: T;
  html?: T;
  text?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  status?: T;
  author?: T;
  featuredImage?: T;
  categories?: T;
  tags?: T;
  scheduledFor?: T;
  publishedAt?: T;
  viewCount?: T;
  commentCount?: T;
  allowComments?: T;
  seo?: T;
  relatedPosts?: T;
  relatedStories?: T;
  relatedGuides?: T;
  relatedTourTypes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  order?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  authorName?: T;
  authorEmail?: T;
  authorUrl?: T;
  content?: T;
  status?: T;
  parent?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  altText?: T;
  caption?: T;
  description?: T;
  mediaType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  code?: T;
  company?: T;
  name?: T;
  summary?: T;
  itinerary?: T;
  startDate?: T;
  endDate?: T;
  clientCount?: T;
  clientCountry?: T;
  clientCity?: T;
  guides?: T;
  status?: T;
  showFeedbackForm?: T;
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        url?: T;
        id?: T;
      };
  provinces?: T;
  tourTypes?: T;
  clientNationalities?: T;
  guideLanguages?: T;
  relatedPosts?: T;
  relatedStories?: T;
  price?: T;
  currency?: T;
  priceUnit?: T;
  durationDays?: T;
  groupSizeMin?: T;
  groupSizeMax?: T;
  departureSchedule?: T;
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-comments_select".
 */
export interface TourCommentsSelect<T extends boolean = true> {
  tour?: T;
  authorName?: T;
  rating?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  language?: T;
  rating?: T;
  message?: T;
  tour?: T;
  photo?: T;
  status?: T;
  source?: T;
  externalUrl?: T;
  reviewTitle?: T;
  visible?: T;
  featured?: T;
  feedbackSummary?: T;
  guide?: T;
  tourRef?: T;
  approvedAt?: T;
  review?: T;
  rejectedAt?: T;
  rejectedBy?: T;
  rejectionReason?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  authorDisplay?: T;
  country?: T;
  language?: T;
  rating?: T;
  message?: T;
  tour?: T;
  tourName?: T;
  photoUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  status?: T;
  summary?: T;
  reviewType?: T;
  approvedAt?: T;
  feedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  phone?: T;
  email?: T;
  cardNumber?: T;
  cardType?: T;
  cardIssuePlace?: T;
  cardIssueDate?: T;
  cardExpiryDate?: T;
  experienceYears?: T;
  bio?: T;
  slogan?: T;
  guideFeeUsd?: T;
  showOnFrontend?: T;
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
        whatsapp?: T;
        zalo?: T;
        viber?: T;
        linkedin?: T;
      };
  spokenLanguages?:
    | T
    | {
        language?: T;
        level?: T;
        certificate?: T;
        id?: T;
      };
  provinces?: T;
  nationalities?: T;
  tourTypes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nationalities_select".
 */
export interface NationalitiesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-types_select".
 */
export interface TourTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  publishedAt?: T;
  readTimeMinutes?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  category?: T;
  relatedGuides?: T;
  relatedTourTypes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  description?: T;
  heroImage?: T;
  province?: T;
  order?: T;
  status?: T;
  tours?: T;
  tourTypes?: T;
  guides?: T;
  posts?: T;
  stories?: T;
  mustSee?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  mustDo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  mustEat?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  seo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  relatedTo?: T;
  category?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  key?: T;
  group?: T;
  value?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides_select".
 */
export interface SlidesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  buttonText?: T;
  buttonLink?: T;
  image?: T;
  order?: T;
  active?: T;
  status?: T;
  overlayOpacity?: T;
  alt?: T;
  startAt?: T;
  endAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus_select".
 */
export interface NavigationMenusSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  published?: T;
  items?:
    | T
    | {
        label?: T;
        href?: T;
        type?: T;
        order?: T;
        parentId?: T;
        icon?: T;
        target?: T;
        visibleFor?:
          | T
          | {
              audience?: T;
              id?: T;
            };
        badge?: T;
        area?: T;
        group?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logoLight?: T;
  logoDark?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroCtaLabel?: T;
  heroMedia?: T;
  aboutTitle?: T;
  aboutDescription?: T;
  aboutImage?: T;
  missionStatement?: T;
  values?:
    | T
    | {
        value?: T;
        id?: T;
      };
  contact?: T;
  social?: T;
  copyright?: T;
  primaryColor?: T;
  accentColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  primaryFont?: T;
  secondaryFont?: T;
  primaryColor?: T;
  secondaryColor?: T;
  accentColor?: T;
  backgroundColor?: T;
  textColor?: T;
  linkColor?: T;
  headerStyle?: T;
  footerStyle?: T;
  customCSS?: T;
  customJS?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}